config/routes.rb
Slop::Application.routes.draw do
  
  resources :ebvs

  resources :mediciones

  resources :mediciontipos

  resources :catfiscales

  resources :cotizaciones

  resources :monedas

  resources :eventos

  resources :eventotipos

  resources :tareas

  resources :transacciontipos

  match '/transacciones/filtrosinforme' => 'transacciones#filtrosinforme', via: [:get]
  get '/transacciones/informe', to: 'transacciones#informe', :as => :transacciones_informe
  post '/transaccion/dibujaPantalla', to: 'transacciones#dibujaPantalla', :as => :dibujapantalla_transaccion
  get '/transacciones/cerrar', to: 'transacciones#cerrar', :as => :transacciones_cerrar
  post '/transacciones/aplicar', to: 'transacciones#aplicaCuotasRemoto'
	resources :transacciones

 

 
  match '/cuotas/importe' => 'cuotas#importe', via: [:post]
  match '/cuotas/buscaCuotas' => 'cuotas#buscaCuotas', via: [:post]
  resources :cuotas

	get '/eerr', to: 'asientos#eerr', :as => :eerr
  get '/cashflow', to: 'asientos#cashflow', :as => :cashflow_asiento
  match '/asientos/index' => 'asientos#index', via: [:get]
  resources :asientos

 
  resources :cuentas do
  	post 'importar', on: :collection
  end	
  match '/cuentas/filtraPorTipos' => 'cuentas#filtraPorTipos', via: [:post]
 
  resources :empresas

  resources :establecimientos

  resources :tipo_accs

  resources :movimientos do
		post 'sel', :on => :collection
		resources :movorigen  
	end

  resources :categories

  resources :cat_tipos

  resources :animals

  resources :estados

  resources :rodeos
  	
  
  resources :users

  get '/sessions/cambioEst/:establecimiento_id', to: 'sessions#cambioEst', :as => :cambioEst
  get '/sessions/cambioEmp/:empresa_id', to: 'sessions#cambioEmp', :as => :cambioEmp
  get 'logout', to: 'sessions#logout', :as => :logout
  
  resources :sessions

  resources :tipo_accs

  resources :existencias

  match '/planilla_mensuals/consulta' => 'planilla_mensuals#consulta', via: :all, :as => :planilla_consulta
  resources :planilla_mensuals 

root :to => 'bienvenidos#index'

end

app/models/establecimiento.rb
class Establecimiento < ActiveRecord::Base
	attr_accessible :codigo, :nombre, :user_ids, :users, :clima
	has_many :permisos
	has_many :users, through: :permisos 
	has_many :eventos	
end

app/controllers/establecimientos_controller.rb
class EstablecimientosController < ApplicationController
  before_action :set_establecimiento, only: [:show, :edit, :update, :destroy]

  # GET /establecimientos
  def index
    @establecimientos = @current_user.establecimientos.where("permiso = 1")
  end

  # GET /establecimientos/1
  def show
  end

  # GET /establecimientos/new
  def new
    @establecimiento = Establecimiento.new
    @usuarios = User.all
    
  end

  # GET /establecimientos/1/edit
  def edit
  	
  	@establecimiento = Establecimiento.find(params[:id])
  	@sel = @establecimiento.user_ids
  	@usuarios = User.all
  	
  end

  # POST /establecimientos
  def create
    @establecimiento = Establecimiento.new(establecimiento_params)
    @establecimiento.update_attributes(:user_ids => @current_user.id)

    if @establecimiento.save
      redirect_to @establecimiento, notice: 'Establecimiento was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /establecimientos/1
  def update
    if @establecimiento.update(establecimiento_params)
    	    @establecimiento.update_attributes(:user_ids => params[:users])
      redirect_to @establecimiento, notice: 'Establecimiento was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /establecimientos/1
  def destroy
    @establecimiento.destroy
    redirect_to establecimientos_url, notice: 'Establecimiento was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_establecimiento
      @establecimiento = Establecimiento.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def establecimiento_params
      params.require(:establecimiento).permit(:codigo, :nombre, :clima)
    end
end

app/helpers/establecimientos_helper.rb
module EstablecimientosHelper
end

app/views/establecimientos/_form.html.erb
<div class="row">
	<div class="small-12 columns">
<%= form_for(@establecimiento) do |f| %>
  <% if @establecimiento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@establecimiento.errors.count, "error") %> prohibited this establecimiento from being saved:</h2>

      <ul>
      <% @establecimiento.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row collapse">
 <div class="small-2 columns">
      <span class="prefix">CODIGO</span>
  </div>
	<div class="small-10 columns">
    <%= f.text_field :codigo %>
	</div>
</div>
<div class="row collapse">
 <div class="small-2 columns">
      <span class="prefix">NOMBRE</span>
  </div>
	<div class="small-10 columns">
    <%= f.text_field :nombre %>
	</div>
</div>

<div class="row collapse">
 <div class="small-2 columns">
      <span class="prefix">Clima (escribir html del widget)</span>
  </div>
	<div class="small-10 columns">
    <%= f.text_area :clima %>
	</div>
</div>


<div class="row">
	<div class="small-12 columns">
	  <%= select_tag "users" , options_from_collection_for_select(@usuarios, :id, :usuario,@sel), :multiple => true %>
	</div>
</div>
<div class="row">
	<div class="small-6 columns">
    <%= f.submit "GUARDAR", :class => "button", :style => "width:100%" %>
	</div>
	<div class="small-6 columns">
	<button class="button" onclick="window.location.href='<%= establecimientos_path %>';return false" style="width:100%">VOLVER</button>
	</div>

</div>

<% end %>

</div>

app/views/establecimientos/edit.html.erb
<h1>EDITAR ESTABLECIMIENTO</h1>

<%= render 'form' %>

app/views/establecimientos/index.html.erb
<h1>ESTABLECIMIENTOS</h1>

<div class="row">
	<div class="small-12 large-12 columns">
		<div class="panel">
			<table style="width:100%">
  <thead>
    <tr>
      <th>CODIGO</th>
      <th>NOMBRE</th>
			<th></th>

    </tr>
  </thead>

  <tbody>
    <% @establecimientos.each do |establecimiento| %>
						<tr onclick="window.location.href='<%= edit_establecimiento_path(establecimiento)%>'">
        <td><%= establecimiento.codigo %></td>
        <td><%= establecimiento.nombre %></td>
        <td><%= link_to image_tag("borrar.png", :height => 20, :border=>0), establecimiento, method: :delete, data: { confirm: 'Esta seguro que desea borrar el registro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
	</div>
</div>

<div class="row">
	<div class="small-12 large-12 columns">
		<div class="panel">
			<center>
			<a href="<%= new_establecimiento_path %>">
					<input type="button" value="CREAR NUEVO ESTABLECIMIENTO" class="button"/>
			</a>
			</center>
		</div> 
	</div>
</div>

app/views/establecimientos/new.html.erb
<h1>CREAR ESTABLECIMIENTO</h1>

<%= render 'form' %>

<%= link_to image_tag("volver.png", :height => 40, :border=>0), establecimientos_path %>

app/views/establecimientos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Codigo:</strong>
  <%= @establecimiento.codigo %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @establecimiento.nombre %>
</p>

<%= link_to 'Edit', edit_establecimiento_path(@establecimiento) %> |
<%= link_to 'Back', establecimientos_path %>