config/routes.rb
Slop::Application.routes.draw do
  
  resources :ebvs

  resources :mediciones

  resources :mediciontipos

  resources :catfiscales

  resources :cotizaciones

  resources :monedas

  resources :eventos

  resources :eventotipos

  resources :tareas

  resources :transacciontipos

  match '/transacciones/filtrosinforme' => 'transacciones#filtrosinforme', via: [:get]
  get '/transacciones/informe', to: 'transacciones#informe', :as => :transacciones_informe
  post '/transaccion/dibujaPantalla', to: 'transacciones#dibujaPantalla', :as => :dibujapantalla_transaccion
  get '/transacciones/cerrar', to: 'transacciones#cerrar', :as => :transacciones_cerrar
  post '/transacciones/aplicar', to: 'transacciones#aplicaCuotasRemoto'
	resources :transacciones

 

 
  match '/cuotas/importe' => 'cuotas#importe', via: [:post]
  match '/cuotas/buscaCuotas' => 'cuotas#buscaCuotas', via: [:post]
  resources :cuotas

	get '/eerr', to: 'asientos#eerr', :as => :eerr
  get '/cashflow', to: 'asientos#cashflow', :as => :cashflow_asiento
  match '/asientos/index' => 'asientos#index', via: [:get]
  resources :asientos

 
  resources :cuentas do
  	post 'importar', on: :collection
  end	
  match '/cuentas/filtraPorTipos' => 'cuentas#filtraPorTipos', via: [:post]
 
  resources :empresas

  resources :establecimientos

  resources :tipo_accs

  resources :movimientos do
		post 'sel', :on => :collection
		resources :movorigen  
	end

  resources :categories

  resources :cat_tipos

  resources :animals

  resources :estados

  resources :rodeos
  	
  
  resources :users

  get '/sessions/cambioEst/:establecimiento_id', to: 'sessions#cambioEst', :as => :cambioEst
  get '/sessions/cambioEmp/:empresa_id', to: 'sessions#cambioEmp', :as => :cambioEmp
  get 'logout', to: 'sessions#logout', :as => :logout
  
  resources :sessions

  resources :tipo_accs

  resources :existencias

  match '/planilla_mensuals/consulta' => 'planilla_mensuals#consulta', via: :all, :as => :planilla_consulta
  resources :planilla_mensuals 

root :to => 'bienvenidos#index'

end

app/models/mediciontipo.rb
class Mediciontipo < ActiveRecord::Base
end

app/controllers/mediciontipos_controller.rb
class MediciontiposController < ApplicationController
  before_action :set_mediciontipo, only: [:show, :edit, :update, :destroy]

  # GET /mediciontipos
  def index
    @mediciontipos = Mediciontipo.all
  end

  # GET /mediciontipos/1
  def show
  end

  # GET /mediciontipos/new
  def new
    @mediciontipo = Mediciontipo.new
  end

  # GET /mediciontipos/1/edit
  def edit
  end

  # POST /mediciontipos
  def create
    @mediciontipo = Mediciontipo.new(mediciontipo_params)

    if @mediciontipo.save
      redirect_to @mediciontipo, notice: 'Mediciontipo was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /mediciontipos/1
  def update
    if @mediciontipo.update(mediciontipo_params)
      redirect_to @mediciontipo, notice: 'Mediciontipo was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /mediciontipos/1
  def destroy
    @mediciontipo.destroy
    redirect_to mediciontipos_url, notice: 'Mediciontipo was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mediciontipo
      @mediciontipo = Mediciontipo.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def mediciontipo_params
      params.require(:mediciontipo).permit(:codigo, :nombre)
    end
end

app/helpers/mediciontipos_helper.rb
module MediciontiposHelper
end

app/views/mediciontipos/_form.html.erb
<div class="row">
	<div class="small-12 columns">
		<div class="panel">
<%= form_for(@mediciontipo) do |f| %>
  <% if @mediciontipo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mediciontipo.errors.count, "error") %> prohibited this mediciontipo from being saved:</h2>

      <ul>
      <% @mediciontipo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :codigo %><br>
    <%= f.number_field :codigo %>
  </div>
  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="actions">
   <%= f.submit "GUARDAR", :class => 'button', :style => 'width:100%' %>
  </div>
<% end %>
</div>
	</div>
</div>

app/views/mediciontipos/edit.html.erb
<h1>Editing mediciontipo</h1>

<%= render 'form' %>

<%= link_to image_tag("volver.png", :height => 40, :border=>0), mediciontipos_path %>

app/views/mediciontipos/index.html.erb
<h1>MEDICIONTIPOS</h1>
<div class="row">
	<div class="small-12 large-12 columns">
		<div class="panel">
			<table style="width:100%">
  <thead>
    <tr>
      <th>Codigo</th>
      <th>Nombre</th>
      <th></th>
      <th></th>  
    </tr>
  </thead>

  <tbody>
    <% @mediciontipos.each do |mediciontipo| %>
      <tr>
        <td><%= mediciontipo.codigo %></td>
        <td><%= mediciontipo.nombre %></td>
         <td><%= link_to image_tag("editar.png", :height => 20, :border=>0), edit_mediciontipo_path(mediciontipo) %></td>
        <td><%= link_to image_tag("borrar.png", :height => 20, :border=>0), mediciontipo, method: :delete, data: { confirm: 'Esta seguro que desea borrar el registro?' } %></td>
  </tr>
      </tr>
    <% end %>
  </tbody>
</table>
		</div>
		</div>
	</div>
<div class="row">
	<div class="small-12 large-12 columns">
		<div class="panel">
	<%= link_to 'Crear Mediciontipo', new_mediciontipo_path, :class => 'button', :style=> 'width:100%' %>
		</div> 
	</div>
</div>

app/views/mediciontipos/new.html.erb
<h1>Nuevo MEDICIONTIPO</h1>

<%= render 'form' %>

app/views/mediciontipos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Codigo:</strong>
  <%= @mediciontipo.codigo %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @mediciontipo.nombre %>
</p>

<%= link_to 'Edit', edit_mediciontipo_path(@mediciontipo) %> |