config/routes.rb
Slop::Application.routes.draw do
  
  resources :ebvs

  resources :mediciones

  resources :mediciontipos

  resources :catfiscales

  resources :cotizaciones

  resources :monedas

  resources :eventos

  resources :eventotipos

  resources :tareas

  resources :transacciontipos

  match '/transacciones/filtrosinforme' => 'transacciones#filtrosinforme', via: [:get]
  get '/transacciones/informe', to: 'transacciones#informe', :as => :transacciones_informe
  post '/transaccion/dibujaPantalla', to: 'transacciones#dibujaPantalla', :as => :dibujapantalla_transaccion
  get '/transacciones/cerrar', to: 'transacciones#cerrar', :as => :transacciones_cerrar
  post '/transacciones/aplicar', to: 'transacciones#aplicaCuotasRemoto'
	resources :transacciones

 

 
  match '/cuotas/importe' => 'cuotas#importe', via: [:post]
  match '/cuotas/buscaCuotas' => 'cuotas#buscaCuotas', via: [:post]
  resources :cuotas

	get '/eerr', to: 'asientos#eerr', :as => :eerr
  get '/cashflow', to: 'asientos#cashflow', :as => :cashflow_asiento
  match '/asientos/index' => 'asientos#index', via: [:get]
  resources :asientos

 
  resources :cuentas do
  	post 'importar', on: :collection
  end	
  match '/cuentas/filtraPorTipos' => 'cuentas#filtraPorTipos', via: [:post]
 
  resources :empresas

  resources :establecimientos

  resources :tipo_accs

  resources :movimientos do
		post 'sel', :on => :collection
		resources :movorigen  
	end

  resources :categories

  resources :cat_tipos

  resources :animals

  resources :estados

  resources :rodeos
  	
  
  resources :users

  get '/sessions/cambioEst/:establecimiento_id', to: 'sessions#cambioEst', :as => :cambioEst
  get '/sessions/cambioEmp/:empresa_id', to: 'sessions#cambioEmp', :as => :cambioEmp
  get 'logout', to: 'sessions#logout', :as => :logout
  
  resources :sessions

  resources :tipo_accs

  resources :existencias

  match '/planilla_mensuals/consulta' => 'planilla_mensuals#consulta', via: :all, :as => :planilla_consulta
  resources :planilla_mensuals 

root :to => 'bienvenidos#index'

end

app/models/ebv.rb
class Ebv < ActiveRecord::Base
  belongs_to :animal
end

app/controllers/ebvs_controller.rb
class EbvsController < ApplicationController
  before_action :set_ebv, only: [:show, :edit, :update, :destroy]

  # GET /ebvs
  def index
    @ebvs = Ebv.all
  end

  # GET /ebvs/1
  def show
  end

  # GET /ebvs/new
  def new
    @ebv = Ebv.new
  end

  # GET /ebvs/1/edit
  def edit
  end

  # POST /ebvs
  def create
    @ebv = Ebv.new(ebv_params)

    if @ebv.save
      redirect_to @ebv, notice: 'Ebv was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /ebvs/1
  def update
    if @ebv.update(ebv_params)
      redirect_to @ebv, notice: 'Ebv was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /ebvs/1
  def destroy
    @ebv.destroy
    redirect_to ebvs_url, notice: 'Ebv was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ebv
      @ebv = Ebv.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def ebv_params
      params.require(:ebv).permit(:fecha, :nacdird, :nacdirp, :nacmatd, :nacmatp, :dttdird, :dttdirp, :dttmatd, :dttmatp, :pasoad, :pesoap, :pesoaymd, :pesoaymp, :pesoadd, :pesoadp, :gdpd, :gdpp, :icad, :icap, :consumod, :consumop, :irfd, :irfp, :althd, :althp, :largod, :largop, :ctd, :ctp, :ced, :cep, :animal_id)
    end
end

app/helpers/ebvs_helper.rb
module EbvsHelper
end

app/views/ebvs/_form.html.erb
<div class="row">
	<div class="small-12 columns">
		<div class="panel">
<%= form_for(@ebv) do |f| %>
  <% if @ebv.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ebv.errors.count, "error") %> prohibited this ebv from being saved:</h2>

      <ul>
      <% @ebv.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fecha %><br>
    <%= f.date_select :fecha %>
  </div>
  <div class="field">
    <%= f.label :nacdird %><br>
    <%= f.text_field :nacdird %>
  </div>
  <div class="field">
    <%= f.label :nacdirp %><br>
    <%= f.text_field :nacdirp %>
  </div>
  <div class="field">
    <%= f.label :nacmatd %><br>
    <%= f.text_field :nacmatd %>
  </div>
  <div class="field">
    <%= f.label :nacmatp %><br>
    <%= f.text_field :nacmatp %>
  </div>
  <div class="field">
    <%= f.label :dttdird %><br>
    <%= f.text_field :dttdird %>
  </div>
  <div class="field">
    <%= f.label :dttdirp %><br>
    <%= f.text_field :dttdirp %>
  </div>
  <div class="field">
    <%= f.label :dttmatd %><br>
    <%= f.text_field :dttmatd %>
  </div>
  <div class="field">
    <%= f.label :dttmatp %><br>
    <%= f.text_field :dttmatp %>
  </div>
  <div class="field">
    <%= f.label :pasoad %><br>
    <%= f.text_field :pasoad %>
  </div>
  <div class="field">
    <%= f.label :pesoap %><br>
    <%= f.text_field :pesoap %>
  </div>
  <div class="field">
    <%= f.label :pesoaymd %><br>
    <%= f.text_field :pesoaymd %>
  </div>
  <div class="field">
    <%= f.label :pesoaymp %><br>
    <%= f.text_field :pesoaymp %>
  </div>
  <div class="field">
    <%= f.label :pesoadd %><br>
    <%= f.text_field :pesoadd %>
  </div>
  <div class="field">
    <%= f.label :pesoadp %><br>
    <%= f.text_field :pesoadp %>
  </div>
  <div class="field">
    <%= f.label :gdpd %><br>
    <%= f.text_field :gdpd %>
  </div>
  <div class="field">
    <%= f.label :gdpp %><br>
    <%= f.text_field :gdpp %>
  </div>
  <div class="field">
    <%= f.label :icad %><br>
    <%= f.text_field :icad %>
  </div>
  <div class="field">
    <%= f.label :icap %><br>
    <%= f.text_field :icap %>
  </div>
  <div class="field">
    <%= f.label :consumod %><br>
    <%= f.text_field :consumod %>
  </div>
  <div class="field">
    <%= f.label :consumop %><br>
    <%= f.text_field :consumop %>
  </div>
  <div class="field">
    <%= f.label :irfd %><br>
    <%= f.text_field :irfd %>
  </div>
  <div class="field">
    <%= f.label :irfp %><br>
    <%= f.text_field :irfp %>
  </div>
  <div class="field">
    <%= f.label :althd %><br>
    <%= f.text_field :althd %>
  </div>
  <div class="field">
    <%= f.label :althp %><br>
    <%= f.text_field :althp %>
  </div>
  <div class="field">
    <%= f.label :largod %><br>
    <%= f.text_field :largod %>
  </div>
  <div class="field">
    <%= f.label :largop %><br>
    <%= f.text_field :largop %>
  </div>
  <div class="field">
    <%= f.label :ctd %><br>
    <%= f.text_field :ctd %>
  </div>
  <div class="field">
    <%= f.label :ctp %><br>
    <%= f.text_field :ctp %>
  </div>
  <div class="field">
    <%= f.label :ced %><br>
    <%= f.text_field :ced %>
  </div>
  <div class="field">
    <%= f.label :cep %><br>
    <%= f.text_field :cep %>
  </div>
  <div class="field">
    <%= f.label :animal %><br>
    <%= f.text_field :animal %>
  </div>
  <div class="actions">
   <%= f.submit "GUARDAR", :class => 'button', :style => 'width:100%' %>
  </div>
<% end %>
</div>
	</div>
</div>

app/views/ebvs/edit.html.erb
<h1>Editing ebv</h1>

<%= render 'form' %>

<%= link_to image_tag("volver.png", :height => 40, :border=>0), ebvs_path %>

app/views/ebvs/index.html.erb
<h1>EBVS</h1>
<div class="row">
	<div class="small-12 large-12 columns">
		<div class="panel">
			<table style="width:100%">
  <thead>
    <tr>
      <th>Fecha</th>
      <th>Nacdird</th>
      <th>Nacdirp</th>
      <th>Nacmatd</th>
      <th>Nacmatp</th>
      <th>Dttdird</th>
      <th>Dttdirp</th>
      <th>Dttmatd</th>
      <th>Dttmatp</th>
      <th>Pasoad</th>
      <th>Pesoap</th>
      <th>Pesoaymd</th>
      <th>Pesoaymp</th>
      <th>Pesoadd</th>
      <th>Pesoadp</th>
      <th>Gdpd</th>
      <th>Gdpp</th>
      <th>Icad</th>
      <th>Icap</th>
      <th>Consumod</th>
      <th>Consumop</th>
      <th>Irfd</th>
      <th>Irfp</th>
      <th>Althd</th>
      <th>Althp</th>
      <th>Largod</th>
      <th>Largop</th>
      <th>Ctd</th>
      <th>Ctp</th>
      <th>Ced</th>
      <th>Cep</th>
      <th>Animal</th>
      <th></th>
      <th></th>  
    </tr>
  </thead>

  <tbody>
    <% @ebvs.each do |ebv| %>
      <tr>
        <td><%= ebv.fecha %></td>
        <td><%= ebv.nacdird %></td>
        <td><%= ebv.nacdirp %></td>
        <td><%= ebv.nacmatd %></td>
        <td><%= ebv.nacmatp %></td>
        <td><%= ebv.dttdird %></td>
        <td><%= ebv.dttdirp %></td>
        <td><%= ebv.dttmatd %></td>
        <td><%= ebv.dttmatp %></td>
        <td><%= ebv.pasoad %></td>
        <td><%= ebv.pesoap %></td>
        <td><%= ebv.pesoaymd %></td>
        <td><%= ebv.pesoaymp %></td>
        <td><%= ebv.pesoadd %></td>
        <td><%= ebv.pesoadp %></td>
        <td><%= ebv.gdpd %></td>
        <td><%= ebv.gdpp %></td>
        <td><%= ebv.icad %></td>
        <td><%= ebv.icap %></td>
        <td><%= ebv.consumod %></td>
        <td><%= ebv.consumop %></td>
        <td><%= ebv.irfd %></td>
        <td><%= ebv.irfp %></td>
        <td><%= ebv.althd %></td>
        <td><%= ebv.althp %></td>
        <td><%= ebv.largod %></td>
        <td><%= ebv.largop %></td>
        <td><%= ebv.ctd %></td>
        <td><%= ebv.ctp %></td>
        <td><%= ebv.ced %></td>
        <td><%= ebv.cep %></td>
        <td><%= ebv.animal %></td>
         <td><%= link_to image_tag("editar.png", :height => 20, :border=>0), edit_ebv_path(ebv) %></td>
        <td><%= link_to image_tag("borrar.png", :height => 20, :border=>0), ebv, method: :delete, data: { confirm: 'Esta seguro que desea borrar el registro?' } %></td>
  </tr>
      </tr>
    <% end %>
  </tbody>
</table>
		</div>
		</div>
	</div>
<div class="row">
	<div class="small-12 large-12 columns">
		<div class="panel">
	<%= link_to 'Crear Ebv', new_ebv_path, :class => 'button', :style=> 'width:100%' %>
		</div> 
	</div>
</div>

app/views/ebvs/new.html.erb
<h1>Nuevo EBV</h1>

<%= render 'form' %>

app/views/ebvs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fecha:</strong>
  <%= @ebv.fecha %>
</p>

<p>
  <strong>Nacdird:</strong>
  <%= @ebv.nacdird %>
</p>

<p>
  <strong>Nacdirp:</strong>
  <%= @ebv.nacdirp %>
</p>

<p>
  <strong>Nacmatd:</strong>
  <%= @ebv.nacmatd %>
</p>

<p>
  <strong>Nacmatp:</strong>
  <%= @ebv.nacmatp %>
</p>

<p>
  <strong>Dttdird:</strong>
  <%= @ebv.dttdird %>
</p>

<p>
  <strong>Dttdirp:</strong>
  <%= @ebv.dttdirp %>
</p>

<p>
  <strong>Dttmatd:</strong>
  <%= @ebv.dttmatd %>
</p>

<p>
  <strong>Dttmatp:</strong>
  <%= @ebv.dttmatp %>
</p>

<p>
  <strong>Pasoad:</strong>
  <%= @ebv.pasoad %>
</p>

<p>
  <strong>Pesoap:</strong>
  <%= @ebv.pesoap %>
</p>

<p>
  <strong>Pesoaymd:</strong>
  <%= @ebv.pesoaymd %>
</p>

<p>
  <strong>Pesoaymp:</strong>
  <%= @ebv.pesoaymp %>
</p>

<p>
  <strong>Pesoadd:</strong>
  <%= @ebv.pesoadd %>
</p>

<p>
  <strong>Pesoadp:</strong>
  <%= @ebv.pesoadp %>
</p>

<p>
  <strong>Gdpd:</strong>
  <%= @ebv.gdpd %>
</p>

<p>
  <strong>Gdpp:</strong>
  <%= @ebv.gdpp %>
</p>

<p>
  <strong>Icad:</strong>
  <%= @ebv.icad %>
</p>

<p>
  <strong>Icap:</strong>
  <%= @ebv.icap %>
</p>

<p>
  <strong>Consumod:</strong>
  <%= @ebv.consumod %>
</p>

<p>
  <strong>Consumop:</strong>
  <%= @ebv.consumop %>
</p>

<p>
  <strong>Irfd:</strong>
  <%= @ebv.irfd %>
</p>

<p>
  <strong>Irfp:</strong>
  <%= @ebv.irfp %>
</p>

<p>
  <strong>Althd:</strong>
  <%= @ebv.althd %>
</p>

<p>
  <strong>Althp:</strong>
  <%= @ebv.althp %>
</p>

<p>
  <strong>Largod:</strong>
  <%= @ebv.largod %>
</p>

<p>
  <strong>Largop:</strong>
  <%= @ebv.largop %>
</p>

<p>
  <strong>Ctd:</strong>
  <%= @ebv.ctd %>
</p>

<p>
  <strong>Ctp:</strong>
  <%= @ebv.ctp %>
</p>

<p>
  <strong>Ced:</strong>
  <%= @ebv.ced %>
</p>

<p>
  <strong>Cep:</strong>
  <%= @ebv.cep %>
</p>

<p>
  <strong>Animal:</strong>
  <%= @ebv.animal %>
</p>

<%= link_to 'Edit', edit_ebv_path(@ebv) %> |