config/routes.rb
Slop::Application.routes.draw do
  
  resources :ebvs

  resources :mediciones

  resources :mediciontipos

  resources :catfiscales

  resources :cotizaciones

  resources :monedas

  resources :eventos

  resources :eventotipos

  resources :tareas

  resources :transacciontipos

  match '/transacciones/filtrosinforme' => 'transacciones#filtrosinforme', via: [:get]
  get '/transacciones/informe', to: 'transacciones#informe', :as => :transacciones_informe
  post '/transaccion/dibujaPantalla', to: 'transacciones#dibujaPantalla', :as => :dibujapantalla_transaccion
  get '/transacciones/cerrar', to: 'transacciones#cerrar', :as => :transacciones_cerrar
  post '/transacciones/aplicar', to: 'transacciones#aplicaCuotasRemoto'
	resources :transacciones

 

 
  match '/cuotas/importe' => 'cuotas#importe', via: [:post]
  match '/cuotas/buscaCuotas' => 'cuotas#buscaCuotas', via: [:post]
  resources :cuotas

	get '/eerr', to: 'asientos#eerr', :as => :eerr
  get '/cashflow', to: 'asientos#cashflow', :as => :cashflow_asiento
  match '/asientos/index' => 'asientos#index', via: [:get]
  resources :asientos

 
  resources :cuentas do
  	post 'importar', on: :collection
  end	
  match '/cuentas/filtraPorTipos' => 'cuentas#filtraPorTipos', via: [:post]
 
  resources :empresas

  resources :establecimientos

  resources :tipo_accs

  resources :movimientos do
		post 'sel', :on => :collection
		resources :movorigen  
	end

  resources :categories

  resources :cat_tipos

  resources :animals

  resources :estados

  resources :rodeos
  	
  
  resources :users

  get '/sessions/cambioEst/:establecimiento_id', to: 'sessions#cambioEst', :as => :cambioEst
  get '/sessions/cambioEmp/:empresa_id', to: 'sessions#cambioEmp', :as => :cambioEmp
  get 'logout', to: 'sessions#logout', :as => :logout
  
  resources :sessions

  resources :tipo_accs

  resources :existencias

  match '/planilla_mensuals/consulta' => 'planilla_mensuals#consulta', via: :all, :as => :planilla_consulta
  resources :planilla_mensuals 

root :to => 'bienvenidos#index'

end

app/models/estado.rb
class Estado < ActiveRecord::Base
  attr_accessible :desc, :nombre, :tipo_acc_ids
  has_many :movimientos
  has_many :estado_accions
  has_and_belongs_to_many :cat_tipos
  has_many :tipo_accs, :through => :estado_accions
   
end

app/controllers/estados_controller.rb
class EstadosController < ApplicationController
  # GET /estados
  # GET /estados.json
  def index
    @estados = Estado.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @estados }
    end
  end

  # GET /estados/1
  # GET /estados/1.json
  def show
    @estado = Estado.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @estado }
    end
  end

  # GET /estados/new
  # GET /estados/new.json
  def new
    @estado = Estado.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @estado }
    end
  end

  # GET /estados/1/edit
  def edit
    @estado = Estado.find(params[:id])
  end

  # POST /estados
  # POST /estados.json
  def create
    @estado = Estado.new(params[:estado])

    respond_to do |format|
      if @estado.save
        format.html { redirect_to estados_path, notice: 'Estado was successfully created.' }
        format.json { render json: @estado, status: :created, location: @estado }
      else
        format.html { render action: "new" }
        format.json { render json: @estado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /estados/1
  # PUT /estados/1.json
  def update
    @estado = Estado.find(params[:id])

    respond_to do |format|
      if @estado.update_attributes(params[:estado])
        format.html { redirect_to @estado, notice: 'Estado was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @estado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estados/1
  # DELETE /estados/1.json
  def destroy
    @estado = Estado.find(params[:id])
    @estado.destroy

    respond_to do |format|
      format.html { redirect_to estados_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/estados_helper.rb
module EstadosHelper
end

app/views/estados/_form.html.erb
<%= form_for(@estado) do |f| %>
  <% if @estado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@estado.errors.count, "error") %> prohibited this estado from being saved:</h2>

      <ul>
      <% @estado.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
 
   <div class="field">
    <%= f.label "Descripción" %><br />
    <%= f.text_field :desc %>
  </div>
  <div class="actions">
    <%= f.submit "ENVIAR" %>
  </div>
<% end %>

app/views/estados/edit.html.erb
<h1>EDITAR ESTADOS</h1>

<%= render 'form' %>


<%= link_to image_tag("volver.png", :height => 40, :border=>0), estados_path %>

app/views/estados/index.html.erb
<h1>ESTADOS</h1>

<div class="row">
	<div class="small-12 large-12 columns">
		<div class="panel">
			<table style="width:100%">
				<thead>
  <tr>
    <th>NOMBRE</th>
    <th>DESCRIPCIÓN</th>  
  </tr>
</thead>
<tbody>
<% @estados.each do |estado| %>
  	<tr onclick="window.location.href='<%= edit_estado_path(estado)%>'">
    <td><%= estado.nombre %></td>
    <td><%= estado.desc %></td>
  </tr>
<% end %>
</tbody>
</table>
</div>
	</div>
</div>

<div class="row">
	<div class="small-12 large-12 columns">
		<div class="panel">
			<center>
			<a href="<%= new_estado_path">
					<input type="button" value="CREAR NUEVO ESTADO" class="button"/>
			</a>
			</center>
		</div> 
	</div>
</div>

app/views/estados/new.html.erb
<h1>CREAR ESTADO</h1>

<%= render 'form' %>

<%= link_to image_tag("volver.png", :height => 40, :border=>0), estados_path %>

app/views/estados/show.html.erb
<p>
  <b>Nombre:</b>
  <%= @estado.nombre %>
</p>

<p>
  <b>Desc:</b>
  <%= @estado.desc %>
</p>


<%= link_to 'EDITAR', edit_estado_path(@estado) %> |
<%= link_to 'VOLVER', estados_path %>